"""All user-facing chat strings, English + Spanish.

Every key must exist in BOTH dicts — the engine picks by consultant language.
Keep command words (add/remove/cancel) in English inside ES strings; the
parsers match on them.
"""

UI_EN = {
    "empty_prompt": "Say something like: “new customer Jane Doe …” or “order for Jane Doe: …”",
    "canceled": "Okay — canceled. Ready for your new customer or order.",

    "cust_submit_intro": "Okay — here's the customer I'm about to submit:",
    "name": "Name",
    "email": "Email",
    "phone": "Phone",
    "address": "Address",
    "birthday": "Birthday",
    "none": "(none)",
    "cust_confirm_q": "Does that look right? (yes/no)",
    "cust_edit_hint": "If you need to add or edit just add the correct information in chat.",

    "order_intro": "Okay — I have this order for {first} {last}:",
    "estimated_total": "Estimated retail total: {total}",
    "order_confirm_q": "Does that sound right? (yes/no)",

    "need_customer_for_order": "Who is this order for? Please tell me the customer name and the products they ordered.",
    "need_customer_info": "Okay, tell me the customer's name and information.",
    "need_items": "What items should I add to the order?",
    "got_it_ordering_for": "Got it — order for {name}.",
    "no_matches": "No close matches. Try different words (brand, line, or shade helps), say <strong>skip</strong> to skip this item, or <strong>cancel</strong> to start over.",
    "reply_yes_no_qty": "Reply yes, no, skip, or cancel — or add a quantity like 'x2'",
    "order_adjust_hint": "You can also <strong>add</strong> or <strong>remove</strong> a product, or <strong>cancel</strong> to start over.",

    # ✅ Missing keys your code uses:
    "parse_error": "❌ Parse error: {err}",
    "cant_tell": "I couldn't tell if that was a new customer or an order. Try rephrasing.",
    "cust_confirmed": "✅ {first} {last} confirmed. Adding to MyCustomers now.",
    "cust_reject": "No problem — Send the corrected customer info and I'll try again.",
    "order_confirmed": "✅ Order for {first} {last} confirmed. Sending to MyCustomers now.",
    "order_reject": "Okay — paste the corrected order and I'll rebuild the summary.",

    "no_catalog_match": "I couldn't find that product in the catalog. Try rewording it (brand, line, or shade helps), or say <strong>cancel</strong> to start over.",
    "no_customer_found": "I couldn't find {name} in your saved customers. You can type <strong>help</strong> to see things you can do in chat.",
    "no_customer_found_yet": "I couldn't find {name} in your saved customers yet. You can type <strong>help</strong> to see things you can do in chat.",
    "no_customer_id": "I couldn't find a customer with ID {cid}.",
    "customer_spent": "{name} has spent ${total} ({period}).",
    "who_is_customer": "Who is the customer? Try: \u201cshow Jane\u2019s info\u201d.",
    "multiple_matches": "Multiple matches: Reply with 1, 2, or 3 — or type cancel.",
    "lost_order_draft": "I lost track of that order draft. Please paste the order again.",
    "what_to_do_customer": "Okay — what would you like to do with that customer?",
    "inventory_added": "Added {qty} of {product} to your inventory. You currently have {current} on hand.",
    "inventory_removed": "Removed {qty} of {product} from your inventory. You currently have {current} on hand.",
    "inventory_set": "Set {product} inventory to {qty}. You currently have {current} on hand.",
    "inventory_report": "Here's your inventory report: {link}",
    "reply_yes_no": "Reply yes or no.",
    "pick_match_5": "Pick the best match with 1-5, or type cancel.",
    "low_stock_set": "Got it — I'll flag {product} when you have fewer than {qty} on hand.",
    "confirming_customer": "You're confirming a new customer. Reply yes or no, or type cancel to retry.",
    "deleted_customer": "✅ Deleted {name} from MyPinkAssistant (MyCustomers was not changed).",
    "delete_failed": "I couldn't delete that customer (maybe it was already removed).",
    "delete_confirm_prompt": "To confirm deletion, type DELETE. Or type <strong>cancel</strong>.",
    "no_items_caught": "I didn't catch any items — try again with the product names.",
    "add_hint": "Tell me what to add, e.g. `add satin hands`.",
    "remove_hint": "Tell me what to remove, e.g. `remove 1` or `remove charcoal`.",
    "remove_not_found": "I couldn't find that item to remove. Try `remove 1` or part of the name.",
    "confirming_order": "You're confirming an order. Reply <strong>yes</strong> or <strong>no</strong>, or say <strong>add [product]</strong> or <strong>remove [product]</strong> to edit the order.",
    "reply_yes_no_adjust": "Reply <strong>yes</strong>, <strong>no</strong>, or <strong>cancel</strong>, or tell me to <strong>add [product]</strong> or <strong>remove [product]</strong>.",
    "trouble": "I'm having a little trouble right now, please try again in a moment.",
    "customer_not_in_mc": "I'm not finding {name} in MyCustomers. We will need to add {name} as a new customer first.",
    "propose_top": "I think you mean: {line}. Is that right? (yes/no)",
    "render_top5_intro": "Got it \u2014 select the best match (reply {range}), or type different search words and I'll search again:",

    "submitted_order_edit": "Once an order has been sent to MyCustomers I can't currently edit or remove it from chat. You can delete or change the order in <a href=\"https://apps.marykayintouch.com/customer-list\" target=\"_blank\">MyCustomers</a>, and MyPinkAssistant will get the corrected info on the next sync.",
    "submitted_order_add": "Heads up: we can't currently add to orders already submitted to MyCustomers. If you add the item to the order in <a href=\"https://apps.marykayintouch.com/customer-list\" target=\"_blank\">MyCustomers</a>, it will be added to MyPinkAssistant on the next sync.",

    "notes_educate": "We are working on the ability to add notes to customers. Currently you can log into <a href=\"https://apps.marykayintouch.com/customer-list\" target=\"_blank\">MyCustomers</a> to add or edit notes.",
    "mycustomers_link": "Here's the link to <a href=\"https://apps.marykayintouch.com/customer-list\" target=\"_blank\">MyCustomers</a>&nbsp; <button class=\"fdp-copy copy-link-btn\" data-copy=\"https://apps.marykayintouch.com/customer-list\">Copy Link</button>",
    "bulk_text_educate": "I can't send texts directly to customers, but if you say <strong>Do I have any followups</strong> you can click the tap-to-text button to text a followup message directly from your phone.",

    # Unit / team query strings
    "unit_no_data": "I don't have team data synced for your account yet. Once a report sync runs, I'll be able to answer questions about your team.",
    "unit_query_rephrase": "I had trouble generating a query. Please try rephrasing your question.",
    "unit_query_unclear": "I wasn't able to form a query for that. Try rephrasing \u2014 for example, 'who has MyShop set up' or 'show me inactive consultants'.",
    "unit_read_only": "I can only read data, not modify it. Please ask a question about your team.",
    "unit_unsafe_query": "That query isn't something I can run safely. Please ask a read-only question.",
    "unit_query_error": "I wasn't able to pull that report right now. Try rephrasing, or ask something like 'who doesn't have MyShop set up' or 'who is close to a Great Start bundle'.",
    "data_query_rephrase": "I had trouble forming a query for that. Try rephrasing — for example, 'who ordered in May' or 'how many orders last month'.",
    "data_query_error": "I wasn't able to run that search right now. Try rephrasing your question.",
    "data_query_no_results": "No results found for that search.",
    "unit_member_not_found": "I couldn't find a team member named {name}.",
    "unit_no_results": "No consultants match that criteria.",
    "unit_consultant_count": "{n} consultant (as of the latest sync):",
    "unit_consultants_count": "{n} consultants (as of the latest sync):",
}

UI_ES = {
    "empty_prompt": "Di algo como: “nuevo cliente Jane Doe …” o “pedido para Jane Doe: …”",
    "canceled": "Listo — cancelado. Estoy listo para tu nuevo cliente o pedido.",

    "cust_submit_intro": "Perfecto — este es el cliente que estoy por enviar:",
    "name": "Nombre",
    "email": "Correo",
    "phone": "Teléfono",
    "address": "Dirección",
    "birthday": "Cumpleaños",
    "none": "(ninguno)",
    "cust_confirm_q": "¿Se ve correcto? (sí/no)",
    # keep add/edit commands in English so your parser stays simple
    "cust_edit_hint": "Si necesitas agregar o editar, escribe la información correcta en el chat.",

    "order_intro": "Perfecto — tengo este pedido para {first} {last}:",
    "estimated_total": "Total estimado (precio): {total}",
    "order_confirm_q": "¿Suena bien? (sí/no)",

    "need_customer_for_order": "¿Para quién es este pedido? Dime el nombre del cliente y los productos que ordenó.",
    "need_customer_info": "Perfecto, dime el nombre del cliente y su información.",
    "need_items": "¿Qué artículos debo agregar al pedido?",
    "got_it_ordering_for": "Listo — pedido para {name}.",
    "no_matches": "No encontré coincidencias cercanas. Prueba con otras palabras (marca, línea o tono ayuda), escribe <strong>skip</strong> para omitir este artículo, o <strong>cancel</strong> para empezar de nuevo.",
    "reply_yes_no_qty": "Responde sí/no — o escribe una cantidad como `2` o `x2`.",
    "order_adjust_hint": "También puedes <strong>add</strong> o <strong>remove</strong> un producto, o <strong>cancel</strong> para empezar de nuevo.",

    # ✅ Missing keys your code uses:
    "parse_error": "❌ Error al interpretar: {err}",
    "cant_tell": "No pude determinar si era un cliente nuevo o un pedido. Intenta reformularlo.",
    "cust_confirmed": "✅ {first} {last} confirmado. Agregando a MyCustomers ahora.",
    "cust_reject": "No hay problema — envíame la info corregida del cliente y lo intento de nuevo.",
    "order_confirmed": "✅ Pedido para {first} {last} confirmado. Enviándolo a MyCustomers ahora.",
    "order_reject": "Listo — pega el pedido corregido y lo vuelvo a armar.",

    "no_catalog_match": "No pude encontrar ese producto en el catálogo. Intenta describirlo de otra forma (marca, línea o tono ayuda), o di `cancelar` para empezar de nuevo.",
    "no_customer_found": "No encontré a {name} en tus clientes guardados. Puedes escribir <strong>ayuda</strong> para ver lo que puedes hacer en el chat.",
    "no_customer_found_yet": "Aún no encontré a {name} en tus clientes guardados. Puedes escribir <strong>ayuda</strong> para ver lo que puedes hacer en el chat.",
    "no_customer_id": "No encontré un cliente con ID {cid}.",
    "customer_spent": "{name} ha gastado ${total} ({period}).",
    "who_is_customer": "¿Quién es el cliente? Prueba: \u201cinfo de Jane\u201d.",
    "multiple_matches": "Varias coincidencias: responde con 1, 2 o 3 — o escribe cancelar.",
    "lost_order_draft": "Perdí el borrador del pedido. Por favor, vuelve a pegar el pedido.",
    "what_to_do_customer": "Listo — ¿qué quieres hacer con ese cliente?",
    "inventory_added": "Agregué {qty} de {product} a tu inventario. Actualmente tienes {current} disponibles.",
    "inventory_removed": "Eliminé {qty} de {product} de tu inventario. Actualmente tienes {current} disponibles.",
    "inventory_set": "Actualicé el inventario de {product} a {qty}. Actualmente tienes {current} disponibles.",
    "inventory_report": "Aquí está tu reporte de inventario: {link}",
    "reply_yes_no": "Responde sí o no.",
    "pick_match_5": "Elige la mejor opción del 1 al 5, o escribe cancelar.",
    "low_stock_set": "Listo — te avisaré sobre {product} cuando tengas menos de {qty} disponibles.",
    "confirming_customer": "Estás confirmando un nuevo cliente. Responde sí o no, o escribe cancelar para reintentar.",
    "deleted_customer": "✅ {name} eliminado de MyPinkAssistant (MyCustomers no fue modificado).",
    "delete_failed": "No pude eliminar ese cliente (quizás ya fue removido).",
    "delete_confirm_prompt": "Para confirmar la eliminación, escribe ELIMINAR. O escribe `cancelar`.",
    "no_items_caught": "No detecté ningún artículo — intenta de nuevo con los nombres de los productos.",
    "add_hint": "Dime qué agregar, por ejemplo: `add satin hands`.",
    "remove_hint": "Dime qué eliminar, por ejemplo: `remove 1` o `remove charcoal`.",
    "remove_not_found": "No encontré ese artículo para eliminarlo. Prueba `remove 1` o parte del nombre.",
    "confirming_order": "Estás confirmando un pedido. Responde sí o no, o di agregar o eliminar para editarlo.",
    "reply_yes_no_adjust": "Responde sí o no — o di agregar o eliminar para ajustar el pedido.",
    "trouble": "Estoy teniendo un pequeño problema ahora mismo, por favor intenta de nuevo en un momento.",
    "customer_not_in_mc": "No encuentro a {name} en MyCustomers. Necesitaremos agregar a {name} como nueva cliente primero.",
    "propose_top": "Creo que te refieres a: {line}. ¿Es correcto? (sí/no)",

    "submitted_order_edit": "Una vez que un pedido se envió a MyCustomers, por el momento no puedo editarlo ni eliminarlo desde el chat. Puedes eliminar o cambiar el pedido en <a href=\"https://apps.marykayintouch.com/customer-list\" target=\"_blank\">MyCustomers</a>, y MyPinkAssistant recibirá la información corregida en la próxima sincronización.",
    "submitted_order_add": "Aviso: por el momento no podemos agregar artículos a pedidos ya enviados a MyCustomers. Si agregas el artículo al pedido en <a href=\"https://apps.marykayintouch.com/customer-list\" target=\"_blank\">MyCustomers</a>, se agregará a MyPinkAssistant en la próxima sincronización.",

    "notes_educate": "Estamos trabajando en la posibilidad de agregar notas a los clientes. Por ahora puedes iniciar sesión en <a href=\"https://apps.marykayintouch.com/customer-list\" target=\"_blank\">MyCustomers</a> para agregar o editar notas.",
    "mycustomers_link": "Aquí está el enlace a <a href=\"https://apps.marykayintouch.com/customer-list\" target=\"_blank\">MyCustomers</a>&nbsp; <button class=\"fdp-copy copy-link-btn\" data-copy=\"https://apps.marykayintouch.com/customer-list\">Copy Link</button>",
    "bulk_text_educate": "No puedo enviar mensajes de texto directamente a los clientes, pero si dices <strong>Do I have any followups</strong> puedes tocar el botón de texto para enviar un mensaje de seguimiento directamente desde tu teléfono.",

    # Unit / team query strings
    "unit_no_data": "Aún no tengo datos del equipo sincronizados. Una vez que se realice una sincronización, podré responder preguntas sobre tu equipo.",
    "unit_query_rephrase": "Tuve problemas para generar esa consulta. Por favor, intenta reformularla.",
    "unit_query_unclear": "No pude formular esa consulta. Intenta de otra forma — por ejemplo, '¿quién no tiene MyShop configurado?' o 'muestra consultoras inactivas'.",
    "unit_read_only": "Solo puedo leer datos, no modificarlos. Por favor, hazme una pregunta sobre tu equipo.",
    "unit_unsafe_query": "Esa consulta no es algo que pueda ejecutar de forma segura. Por favor, haz una pregunta de solo lectura.",
    "unit_query_error": "No pude obtener ese reporte en este momento. Intenta reformularlo, o pregunta algo como '¿quién no tiene MyShop configurado?' o '¿quién está cerca de un paquete Gran Inicio?'.",
    "data_query_rephrase": "Tuve problemas para formular una consulta para eso. Intenta reformularlo — por ejemplo, '¿quién ordenó en mayo?' o '¿cuántos pedidos el mes pasado?'.",
    "data_query_error": "No pude ejecutar esa búsqueda ahora mismo. Intenta reformular tu pregunta.",
    "data_query_no_results": "No se encontraron resultados para esa búsqueda.",
    "unit_member_not_found": "No encontré a un miembro del equipo con el nombre {name}.",
    "unit_no_results": "Ninguna consultora coincide con ese criterio.",
    "unit_consultant_count": "{n} consultora:",
    "unit_consultants_count": "{n} consultoras:",
    "render_top5_intro": "Listo \u2014 elige la mejor opción (responde {range}), o escribe otras palabras de búsqueda:",
}
